import type { MK121Bill, MK121Question } from "../drizzle/schema";

const now = new Date();
const hoursFromNow = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000);
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

export const demoUser = {
  id: 1,
  openId: "demo-citizen",
  name: "ישראל ישראלי",
  email: "demo@example.local",
  loginMethod: "demo",
  role: "user" as const,
  ministryId: null,
  createdAt: daysFromNow(-14),
  updatedAt: now,
  lastSignedIn: now,
};

export const demoMinistries = [
  {
    id: 1,
    name: "משרד הבריאות",
    description: "מדיניות בריאות ציבורית, בתי חולים, קופות חולים ובריאות מונעת.",
    icon: "HeartPulse",
    color: "#0ea5e9",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 2,
    name: "משרד התחבורה",
    description: "תחבורה ציבורית, כבישים, בטיחות בדרכים ונגישות בין ערים.",
    icon: "Bus",
    color: "#22c55e",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 3,
    name: "משרד החינוך",
    description: "מערכת החינוך, מורים, תכניות לימוד ושוויון הזדמנויות.",
    icon: "GraduationCap",
    color: "#a855f7",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 4,
    name: "המשרד להגנת הסביבה",
    description: "אקלים, פסולת, איכות אוויר ושמירה על שטחים פתוחים.",
    icon: "Leaf",
    color: "#14b8a6",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 5,
    name: "משרד ראש הממשלה",
    description: "תיאום עבודת הממשלה, מדיניות לאומית, מטה ופרויקטים רוחביים.",
    icon: "Landmark",
    color: "#1d4ed8",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 6,
    name: "משרד הביטחון",
    description: "ביטחון המדינה, צה״ל, תעשיות ביטחוניות ומוכנות לאומית.",
    icon: "Shield",
    color: "#475569",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 7,
    name: "משרד החוץ",
    description: "יחסי חוץ, שגרירויות, הסברה וקשרים בינלאומיים.",
    icon: "Globe",
    color: "#2563eb",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 8,
    name: "משרד האוצר",
    description: "תקציב המדינה, מיסוי, מדיניות כלכלית וניהול כספי ציבור.",
    icon: "Coins",
    color: "#16a34a",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 9,
    name: "משרד המשפטים",
    description: "חקיקה, ייעוץ משפטי, זכויות, רישום ורגולציה משפטית.",
    icon: "Scale",
    color: "#7c3aed",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 10,
    name: "המשרד לביטחון לאומי",
    description: "משטרה, כבאות, שירות בתי הסוהר וביטחון פנים.",
    icon: "Badge",
    color: "#dc2626",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 11,
    name: "משרד הפנים",
    description: "רשויות מקומיות, מרשם אוכלוסין, גבולות מוניציפליים ושירותי פנים.",
    icon: "Building2",
    color: "#0891b2",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 12,
    name: "משרד הרווחה והביטחון החברתי",
    description: "שירותים חברתיים, אוכלוסיות בסיכון, מוגבלויות ורווחת משפחה.",
    icon: "HeartHandshake",
    color: "#be123c",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 13,
    name: "משרד הכלכלה והתעשייה",
    description: "עסקים, תעשייה, תחרות, סחר ותעסוקה כלכלית.",
    icon: "Factory",
    color: "#ea580c",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 14,
    name: "משרד האנרגיה והתשתיות",
    description: "חשמל, גז, מים, אנרגיות מתחדשות ותשתיות לאומיות.",
    icon: "Zap",
    color: "#ca8a04",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 15,
    name: "משרד החקלאות וביטחון המזון",
    description: "חקלאות, מזון, פיקוח וייצור מקומי.",
    icon: "Wheat",
    color: "#65a30d",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 16,
    name: "משרד התקשורת",
    description: "תשתיות תקשורת, אינטרנט, דואר, שידורים ושוק התקשורת.",
    icon: "Radio",
    color: "#9333ea",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 17,
    name: "משרד התרבות והספורט",
    description: "תרבות, אמנות, ספורט, מוסדות תרבות ואירועים לאומיים.",
    icon: "Trophy",
    color: "#db2777",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 18,
    name: "משרד התיירות",
    description: "תיירות נכנסת, פיתוח אתרים, מלונאות ושיווק ישראל בעולם.",
    icon: "Map",
    color: "#0d9488",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 19,
    name: "משרד העלייה והקליטה",
    description: "קליטת עולים, סיוע בתעסוקה, שפה ושילוב חברתי.",
    icon: "Plane",
    color: "#0284c7",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 20,
    name: "משרד הבינוי והשיכון",
    description: "דיור, בנייה, התחדשות עירונית ופתרונות מגורים.",
    icon: "Home",
    color: "#64748b",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 21,
    name: "משרד העבודה",
    description: "שוק העבודה, הכשרות מקצועיות, פיקוח ותעסוקה.",
    icon: "Briefcase",
    color: "#334155",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 22,
    name: "משרד החדשנות, המדע והטכנולוגיה",
    description: "מחקר, חדשנות, מדע יישומי וטכנולוגיות מתקדמות.",
    icon: "Atom",
    color: "#4f46e5",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 23,
    name: "המשרד לשירותי דת",
    description: "שירותי דת, מועצות דתיות, כשרות ונושאי קבורה.",
    icon: "ScrollText",
    color: "#854d0e",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 24,
    name: "המשרד לשוויון חברתי וקידום מעמד האישה",
    description: "שוויון חברתי, אזרחים ותיקים, צעירים וקידום מעמד האישה.",
    icon: "UsersRound",
    color: "#c026d3",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 25,
    name: "משרד ירושלים ומסורת ישראל",
    description: "פיתוח ירושלים, מורשת, מסורת ופרויקטים עירוניים.",
    icon: "Castle",
    color: "#92400e",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 26,
    name: "משרד הנגב, הגליל והחוסן הלאומי",
    description: "פיתוח אזורי, חוסן קהילתי, נגב, גליל ופריפריה.",
    icon: "Mountain",
    color: "#15803d",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 27,
    name: "משרד התפוצות והמאבק באנטישמיות",
    description: "קשר עם יהדות התפוצות, חינוך יהודי ומאבק באנטישמיות.",
    icon: "Network",
    color: "#0369a1",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 28,
    name: "משרד המורשת",
    description: "אתרי מורשת, שימור היסטורי, חינוך למורשת וארכיונים.",
    icon: "Archive",
    color: "#78350f",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 29,
    name: "משרד ההתיישבות והמשימות הלאומיות",
    description: "התיישבות, גרעינים משימתיים, קהילות ופרויקטים לאומיים.",
    icon: "MapPinned",
    color: "#4d7c0f",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 30,
    name: "המשרד לשיתוף פעולה אזורי",
    description: "שיתופי פעולה אזוריים, כלכלה אזורית ופרויקטים חוצי גבולות.",
    icon: "Handshake",
    color: "#0f766e",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
];

export const demoDecisions = [
  {
    id: 101,
    ministryId: 1,
    title: "פתיחת מוקדי רפואה דחופה בפריפריה",
    description: "פיילוט להקמת מוקדי טיפול קהילתיים ביישובים מרוחקים כדי לצמצם עומס על חדרי מיון.",
    category: "major" as const,
    status: "voting" as const,
    proposedBy: 7,
    budget: "12000000.00",
    votingStartsAt: hoursFromNow(-8),
    votingEndsAt: hoursFromNow(40),
    publicVotingStartsAt: hoursFromNow(-8),
    publicVotingEndsAt: hoursFromNow(40),
    totalVoters: 18420,
    votesFor: 842,
    votesAgainst: 316,
    publicVotesFor: 12840,
    publicVotesAgainst: 5580,
    vetoed: false,
    rejectionReason: null,
    createdAt: daysFromNow(-5),
    updatedAt: now,
  },
  {
    id: 102,
    ministryId: 11,
    title: "נתיבי העדפה לאוטובוסים בכניסה לערים",
    description: "הרחבת נתיבי תחבורה ציבורית בשעות עומס והצגת מדד שקיפות לזמני נסיעה.",
    category: "medium" as const,
    status: "voting" as const,
    proposedBy: 8,
    budget: "4500000.00",
    votingStartsAt: hoursFromNow(-20),
    votingEndsAt: hoursFromNow(22),
    publicVotingStartsAt: hoursFromNow(-20),
    publicVotingEndsAt: hoursFromNow(22),
    totalVoters: 15700,
    votesFor: 610,
    votesAgainst: 188,
    publicVotesFor: 10410,
    publicVotesAgainst: 5290,
    vetoed: false,
    rejectionReason: null,
    createdAt: daysFromNow(-7),
    updatedAt: now,
  },
  {
    id: 105,
    ministryId: 8,
    title: "עדכון מדרגות מס לעסקים קטנים",
    description: "בחינת שינוי מדיניות מס לעסקים קטנים כדי לעודד השקעה מקומית והעסקת עובדים חדשים.",
    category: "medium" as const,
    status: "voting" as const,
    proposedBy: 11,
    budget: "0.00",
    votingStartsAt: hoursFromNow(-30),
    votingEndsAt: hoursFromNow(12),
    publicVotingStartsAt: hoursFromNow(-30),
    publicVotingEndsAt: hoursFromNow(12),
    totalVoters: 22100,
    votesFor: 14320,
    votesAgainst: 7780,
    publicVotesFor: 14320,
    publicVotesAgainst: 7780,
    vetoed: false,
    rejectionReason: null,
    createdAt: daysFromNow(-4),
    updatedAt: now,
  },
  {
    id: 106,
    ministryId: 9,
    title: "פרסום נימוקי סגירת תיקי אכיפה ציבוריים",
    description: "הצעה לחייב פרסום נימוקים מקוצרים בהחלטות סגירת תיקים בעלי עניין ציבורי.",
    category: "major" as const,
    status: "voting" as const,
    proposedBy: 12,
    budget: "650000.00",
    votingStartsAt: hoursFromNow(-18),
    votingEndsAt: hoursFromNow(28),
    publicVotingStartsAt: hoursFromNow(-18),
    publicVotingEndsAt: hoursFromNow(28),
    totalVoters: 19800,
    votesFor: 10240,
    votesAgainst: 9560,
    publicVotesFor: 10240,
    publicVotesAgainst: 9560,
    vetoed: false,
    rejectionReason: null,
    createdAt: daysFromNow(-6),
    updatedAt: now,
  },
  {
    id: 103,
    ministryId: 3,
    title: "שעת תגבור שבועית במתמטיקה בחטיבות הביניים",
    description: "הקצאת שעות תגבור לבתי ספר במדד טיפוח גבוה, עם מדידה חודשית של פערים.",
    category: "routine" as const,
    status: "approved" as const,
    proposedBy: 9,
    budget: "900000.00",
    votingStartsAt: daysFromNow(-18),
    votingEndsAt: daysFromNow(-15),
    publicVotingStartsAt: daysFromNow(-18),
    publicVotingEndsAt: daysFromNow(-15),
    totalVoters: 42080,
    votesFor: 30320,
    votesAgainst: 11760,
    publicVotesFor: 30320,
    publicVotesAgainst: 11760,
    vetoed: false,
    rejectionReason: null,
    createdAt: daysFromNow(-24),
    updatedAt: daysFromNow(-15),
  },
  {
    id: 104,
    ministryId: 4,
    title: "אגרת פסולת חד פעמית ברשויות חוף",
    description: "הצעה להטיל אגרת ניקיון עונתית על עסקים שמשתמשים באריזות חד פעמיות באזורי חוף.",
    category: "medium" as const,
    status: "rejected" as const,
    proposedBy: 10,
    budget: "300000.00",
    votingStartsAt: daysFromNow(-32),
    votingEndsAt: daysFromNow(-29),
    publicVotingStartsAt: daysFromNow(-32),
    publicVotingEndsAt: daysFromNow(-29),
    totalVoters: 43500,
    votesFor: 14920,
    votesAgainst: 28580,
    publicVotesFor: 14920,
    publicVotesAgainst: 28580,
    vetoed: true,
    rejectionReason: "רוב הציבור ביקש חלופה הדרגתית יותר.",
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-29),
  },
];

export const demoMK121Cycle = {
  id: 1,
  cycleNumber: 121,
  seasonName: "אביב",
  startDate: daysFromNow(-12),
  endDate: daysFromNow(68),
  status: "active" as const,
  winningBillId: null,
  winningQuestionId: null,
  createdAt: daysFromNow(-12),
  updatedAt: now,
};

export const demoMK121Bills: MK121Bill[] = [
  {
    id: 201,
    cycleId: 1,
    title: "חובת פרסום יומן פגישות של רגולטורים",
    description: "כל רגולטור ציבורי יפרסם אחת לחודש יומן פגישות עם בעלי עניין, כולל נושא הפגישה והגורמים המשתתפים.",
    proposedBy: 1,
    category: "שקיפות",
    votes: 18420,
    isWinner: false,
    status: "voting" as const,
    supporters: 168,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-10),
    updatedAt: now,
  },
  {
    id: 202,
    cycleId: 1,
    title: "החזר אוטומטי על איחור חמור בתחבורה ציבורית",
    description: "נוסע שרכש כרטיס ונסיעתו איחרה מעל 30 דקות יקבל החזר אוטומטי דרך הרב-קו או האפליקציה.",
    proposedBy: 1,
    category: "תחבורה",
    votes: 13270,
    isWinner: false,
    status: "voting" as const,
    supporters: 142,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-8),
    updatedAt: now,
  },
  {
    id: 203,
    cycleId: 1,
    title: "שקיפות",
    description: "חיוב בתי ספר לפרסם מראש רשימת ספרים וחלופות דיגיטליות זולות לפני תחילת שנת הלימודים.",
    proposedBy: 1,
    category: "חינוך",
    votes: 0,
    isWinner: false,
    status: "preliminary" as const,
    supporters: 73,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-3),
    updatedAt: now,
  },
  {
    id: 204,
    cycleId: 1,
    title: "הגבלת זמן ראש הממשלה",
    description: "הצעת חוק לקביעת תקופת כהונה מקסימלית של שמונה שנים לראש ממשלה, ברצף או במצטבר, כדי לחזק תחלופה שלטונית ולצמצם ריכוז כוח ממושך.",
    proposedBy: 1,
    category: "ממשל",
    votes: 21980,
    isWinner: false,
    status: "voting" as const,
    supporters: 214,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-2),
    updatedAt: now,
  },
  {
    id: 205,
    cycleId: 1,
    title: "כל ח״כ חייב להצביע",
    description: "הצעת חוק המחייבת את כל חברי הכנסת להשתתף בכל הצבעה שמגיעה למליאה, כדי לסיים מצב שבו חוקים עוברים ללא נוכחות מלאה. ניתן יהיה להצביע באופן דיגיטלי ומאובטח, כולל אימות כפול או הצבעה חוזרת לאימות במקרה הצורך כדי למנוע זיופים.",
    proposedBy: 1,
    category: "כנסת",
    votes: 17640,
    isWinner: false,
    status: "voting" as const,
    supporters: 191,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-1),
    updatedAt: now,
  },
  {
    id: 206,
    cycleId: 1,
    title: "זירת מידע חיה של שאלות ותשובות בין ח״כ",
    description: "הצעת חוק שתאפשר לכל חבר כנסת לשאול פעם בשנה חבר כנסת אחר שאלה אחת. הח\"כ הנשאל יצלם את עצמו בתשובה; אם התשובה תיערך, גם העריכה וגם התשובה המוקלטת יפורסמו בשקיפות מלאה לציבור.",
    proposedBy: 1,
    category: "פיקוח פרלמנטרי",
    votes: 9870,
    isWinner: false,
    status: "voting" as const,
    supporters: 128,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-1),
    updatedAt: now,
  },
  {
    id: 207,
    cycleId: 1,
    title: "הצעת חוק הבחירות לכנסת — הגנת קול הבוחר, התשפ״ו–2026",
    description:
      "מטרת החוק היא לצמצם אובדן קולות בבחירות לכנסת, לחזק את חופש הבחירה ולאפשר תמיכה ברשימה חדשה או קטנה בלי חשש שהקול יאבד. כל בוחר יהיה רשאי לסמן, לצד בחירתו הראשית, גם רשימת גיבוי אחת. אם הרשימה הראשית לא תעבור את אחוז החסימה, ייחשב הקול כאילו ניתן לרשימת הגיבוי, ובלבד שרשימת הגיבוי עברה את אחוז החסימה.",
    proposedBy: 1,
    category: "בחירות ודמוקרטיה",
    votes: 15480,
    isWinner: false,
    status: "voting" as const,
    supporters: 1000,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(0),
    updatedAt: now,
  },
];

export const demoMK121Questions: MK121Question[] = [
  {
    id: 301,
    cycleId: 1,
    title: "מדוע זמני ההמתנה לרופא מומחה לא מפורסמים לפי אזור?",
    description: "שאילתא לשר הבריאות על פרסום שקוף של זמני המתנה לרופאים מומחים לפי קופה, אזור וסוג התמחות.",
    targetMinistry: "משרד הבריאות",
    ministryId: 1,
    proposedBy: 1,
    urgency: "high" as const,
    votes: 15610,
    isWinner: false,
    status: "voting" as const,
    supporters: 121,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-9),
    updatedAt: now,
  },
  {
    id: 302,
    cycleId: 1,
    title: "מה לוח הזמנים להנגשת תחנות אוטובוס מרכזיות?",
    description: "שאילתא לשרת התחבורה על אבני דרך מחייבות להנגשת תחנות בפריפריה ובערים ערביות.",
    targetMinistry: "משרד התחבורה",
    ministryId: 2,
    proposedBy: 1,
    urgency: "medium" as const,
    votes: 11990,
    isWinner: false,
    status: "voting" as const,
    supporters: 104,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-7),
    updatedAt: now,
  },
  {
    id: 303,
    cycleId: 1,
    title: "דף מקדים: פרסום מדדי אלימות בבתי ספר",
    description: "בקשה לפרסום מדדים רבעוניים על אירועי אלימות וטיפול בהם, בלי לפגוע בפרטיות תלמידים.",
    targetMinistry: "משרד החינוך",
    ministryId: 3,
    proposedBy: 1,
    urgency: "low" as const,
    votes: 0,
    isWinner: false,
    status: "preliminary" as const,
    supporters: 58,
    quorumMet: false,
    createdCycleNumber: 121,
    archivedAt: null,
    createdAt: daysFromNow(-4),
    updatedAt: now,
  },
];

export const demoDelegates = [
  {
    id: 401,
    ministryId: 1,
    userId: 41,
    name: "ד״ר נועה ברק",
    bio: "רופאת משפחה ופעילת בריאות קהילתית, מתמקדת בקיצור תורים ובשירותי פריפריה.",
    values: ["שוויון", "נגישות", "שקיפות"],
    expertise: ["בריאות ציבור", "רפואה קהילתית"],
    profileImage: null,
    endorsements: 1240,
    isActive: true,
    createdAt: daysFromNow(-30),
    updatedAt: now,
  },
  {
    id: 402,
    ministryId: 2,
    userId: 42,
    name: "אמיר לוי",
    bio: "מתכנן תחבורה ציבורית, מקדם נתיבי העדפה ותכנון מבוסס נתונים.",
    values: ["יעילות", "בטיחות", "נגישות"],
    expertise: ["תחבורה ציבורית", "תכנון עירוני"],
    profileImage: null,
    endorsements: 980,
    isActive: true,
    createdAt: daysFromNow(-28),
    updatedAt: now,
  },
  {
    id: 403,
    ministryId: 3,
    userId: 43,
    name: "מיכל כהן",
    bio: "מנהלת בית ספר לשעבר, מתמקדת בצמצום פערים ובחיזוק מורים.",
    values: ["הזדמנות שווה", "מקצועיות", "מדידה"],
    expertise: ["חינוך ציבורי", "הכשרת מורים"],
    profileImage: null,
    endorsements: 1125,
    isActive: true,
    createdAt: daysFromNow(-26),
    updatedAt: now,
  },
];

export const demoDelegateAssignments = [
  {
    userId: 1,
    ministryId: 1,
    delegateId: 401,
    delegateUserId: null,
    votingMethod: "delegate" as const,
    delegateName: "ד״ר נועה ברק",
  },
  {
    userId: 1,
    ministryId: 2,
    delegateId: null,
    delegateUserId: null,
    votingMethod: "direct" as const,
  },
];

export const demoDelegateVotes = [
  { id: 501, decisionId: 101, delegateId: 401, vote: "for" as const, votesRepresented: 860, createdAt: hoursFromNow(-4) },
  { id: 502, decisionId: 102, delegateId: 402, vote: "against" as const, votesRepresented: 240, createdAt: hoursFromNow(-6) },
];

export const demoPublicVotes = [
  { id: 601, decisionId: 101, userId: 1, vote: "for" as const, createdAt: hoursFromNow(-3) },
  { id: 602, decisionId: 102, userId: 1, vote: "against" as const, createdAt: hoursFromNow(-2) },
];

export const getDemoMinistry = (id: number) => demoMinistries.find((ministry) => ministry.id === id) ?? null;

const demoVisibleMinistryIds = new Set([1, 2, 3, 4, 5, 8, 9, 11, 12]);

export const getVisibleDemoMinistries = () => [
  {
    id: 8,
    name: "משרד האוצר",
    description: "ניהול תקציב המדינה, מדיניות כלכלית, מיסוי, השקעות.",
    icon: "Coins",
    color: "#16a34a",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 11,
    name: "משרד הפנים, החברה והרווחה",
    description: "רשויות מקומיות, פיתוח כפרי, רווחה חברתית, שירותים לאזרח.",
    icon: "Building2",
    color: "#0891b2",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 6,
    name: "משרד הביטחון",
    description: "ביטחון המדינה, פיקוח על צה״ל, מדיניות אסטרטגית.",
    icon: "Shield",
    color: "#475569",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 9,
    name: "משרד המשפטים",
    description: "ייעוץ משפטי, מערכת המשפט, חקיקה, אכיפה.",
    icon: "Scale",
    color: "#7c3aed",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 4,
    name: "משרד החדשנות ואיכות הסביבה",
    description: "קידום טכנולוגיה, אנרגיה ירוקה, מדיניות סביבתית, חדשנות.",
    icon: "Leaf",
    color: "#14b8a6",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 7,
    name: "משרד החוץ וההסברה העולמית",
    description: "יחסים בינלאומיים, דיפלומטיה, תדמית המדינה, הסברה.",
    icon: "Globe",
    color: "#2563eb",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 3,
    name: "משרד החינוך",
    description: "מערכת החינוך, פיתוח תוכניות לימוד, רווחת תלמידים.",
    icon: "GraduationCap",
    color: "#a855f7",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 1,
    name: "משרד הבריאות",
    description: "מערכת הבריאות, קידום בריאות, רפואה ציבורית.",
    icon: "HeartPulse",
    color: "#0ea5e9",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
  {
    id: 17,
    name: "משרד התרבות",
    description: "תרבות, אמנות, ספורט, זהות תרבותית.",
    icon: "Trophy",
    color: "#db2777",
    createdAt: daysFromNow(-90),
    updatedAt: now,
  },
];

export const getDemoDecisionsByMinistry = (ministryId: number) =>
  demoDecisions.filter((decision) => decision.ministryId === ministryId);

const demoExpertNames = [
  "יעל בן דוד",
  "דניאל מזרחי",
  "רונית אלקיים",
  "עמרי שפירא",
  "ליאת גבאי",
  "אורי פרץ",
];

export const getDemoDelegatesForMinistry = (ministryId: number) => {
  const existingDelegates = demoDelegates
    .filter((delegate) => delegate.ministryId === ministryId && delegate.isActive)
    .map((delegate) => ({
      ...delegate,
      ministryName: getDemoMinistry(delegate.ministryId)?.name ?? "משרד דמו",
    }));

  if (existingDelegates.length > 0) return existingDelegates;

  const ministry = getDemoMinistry(ministryId);
  const ministryName = ministry?.name ?? "משרד דמו";
  const baseId = ministryId * 1000;

  return [0, 1, 2].map((index) => ({
    id: baseId + index + 1,
    ministryId,
    userId: baseId + 101 + index,
    name: demoExpertNames[(ministryId + index) % demoExpertNames.length],
    bio: `מומחה/ית מדיניות בתחום ${ministryName}, עם ניסיון בבחינת החלטות ציבוריות וניתוח השפעות על אזרחים.`,
    values: ["שקיפות", "אחריות ציבורית", "שיקול מקצועי"],
    expertise: [`מדיניות ${ministryName.replace("משרד ", "").replace("המשרד ", "")}`, "ניתוח החלטות", "שיתוף ציבור"],
    profileImage: null,
    endorsements: 520 + ministryId * 17 + index * 83,
    isActive: true,
    createdAt: daysFromNow(-20 - index),
    updatedAt: now,
    ministryName,
  }));
};

export const getDemoDecisionVotes = (decisionId: number) => {
  const decision = demoDecisions.find((item) => item.id === decisionId);
  return {
    for: decision?.votesFor ?? 0,
    against: decision?.votesAgainst ?? 0,
  };
};

export const getDemoPublicVotes = (decisionId: number) => {
  const decision = demoDecisions.find((item) => item.id === decisionId);
  return {
    for: decision?.publicVotesFor ?? 0,
    against: decision?.publicVotesAgainst ?? 0,
  };
};
